#!/bin/bash
# vi: et sts=4 sw=4 ts=4

# Shortcut for 'svn add'

# Copyright (C) 2021-2022 Dan Church.
# License GPLv3: GNU GPL version 3.0 (https://www.gnu.org/licenses/gpl-3.0.html)
# with Commons Clause 1.0 (https://commonsclause.com/).
# This is free software: you are free to change and redistribute it.
# There is NO WARRANTY, to the extent permitted by law.
# You may NOT use this software for commercial purposes.

if [[ -z $SVN ]]; then
    printf 'Missing environment variable "SVN"\n' \
        >&2
    exit 1
fi

exec \
"$SVN" add "$@"
