#!/bin/bash
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# You can set your favourite wallpaper here if you don't want
# to do it from your style.
#
# bsetbg -f ~/pictures/wallpaper.png
#
# This sets a black background
# /usr/bin/bsetroot -solid black

# This shows the fluxbox-splash-screen
# fbsetbg -C /usr/share/fluxbox/splash.jpg

# Other examples. Check man xset for details.
#
# Turn off beeps:
# xset -b
#
# Increase the keyboard repeat-rate:
xset r rate 145 45
# Increase mouse acceleration:
xset m 30/10
# Set DPMS timeouts
xset dpms 0 0 600

xrandr --output VGA-0 --right-of LVDS-0 --auto

# syndaemon disables the trackpad while typing
#syndaemon -i 1 -KR &

# Your own fonts-dir:
if [[ -d ~/.font/ohsnapmod ]]; then
    xset +fp ~/.font/ohsnapmod
fi

#
# Your favourite mouse cursor:
# xsetroot -cursor_name right_ptr
#
# Change your keymap:
# xmodmap ~/.Xmodmap

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# restore last wallpaper (~/.fluxbox/lastwallpaper)
fbsetbg -l

# start the autolocker (default 10 minutes)
xautolock -detectsleep -time 30 &

# start pager
#fbpager -w & # deprecated
#ipager &

if [[ -x /etc/rc.d/rc.networkmanager ]]; then
    nm-applet &
fi

# start root-tail
if [[ -x ~/.fluxbox/bin/root-tail.sh ]]; then
    ~/.fluxbox/bin/root-tail.sh &
fi

# start conky
#conky -q &

# start Dropbox
if [[ -x ~/.dropbox-dist/dropboxd ]]; then
    ~/.dropbox-dist/dropboxd &
fi

#qjackctl &
volumeicon &
gkrellm -w &
wmstickynotes &
redshift &
~/.dropbox-dist/dropboxd &
xscreensaver &

if [ -e /proc/acpi/battery ]; then
	batterymon \
		--theme=16x16 \
		--on-critical=~/bin/batt-warn-shutdown &
fi

# XXX : hack: wpa_gui won't detect system tray until fluxbox is up and running
#(sleep 10s ; exec wpa_gui -t) &
#wpa_gui -t &

nm-applet &

# open up a terminal
xterm -e 'TERM=xterm-256color tmux new -A -s main' &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.


# Start the window manager:
if [ -z "$DESKTOP_SESSION" -a -x /usr/bin/ck-launch-session ]; then
	exec ck-launch-session fluxbox
else
   exec fluxbox
fi

# or if you want to keep a log:
# exec fluxbox -log ~/.fluxbox/log
