#!/bin/bash
# vi: et sts=4 sw=4 ts=4

COLOR=${3:-white}
EXEC=$1
NAME=${2:-$EXEC}
if [[ -n $EXEC ]]; then
    tmux new-window -n "$NAME" "$EXEC"
    tmux set -q window-status-format         "#[fg=$COLOR]#I:#W#F"
    tmux set -q window-status-current-format "#[fg=$COLOR,reverse]#I:#W#F"
fi
