#!/bin/bash

SERVERS=(
    test223.g2planet.com
    test220.g2planet.com
    prod223a.g2planet.com
)

for sv in "${SERVERS[@]}"; do
    ssh "$sv" 'if [[ -x ~/.gitrepos/update.sh ]]; then cd ~/.gitrepos && ./update.sh; fi' 2>&1 |sed -e "s,^,$sv: ," &
done

# update locally
if [[ -x ~/.gitrepos/update.sh ]]; then
    cd ~/.gitrepos &&
        ./update.sh 2>&1 |sed -e 's,^,localhost: ,' &
fi

wait
