#!/bin/bash

# update locally
if [[ -x ~/.gitrepos/update.sh ]]; then
    cd ~/.gitrepos &&
        ./update.sh 2>&1 |sed -e 's,^,localhost: ,' &
fi

if [[ -x /media/expand-dong/git/update.sh ]]; then
    cd /media/expand-dong/git/ &&
        ./update.sh 2>&1 |sed -e 's,^,ed: ,' &
fi

pssh \
    -P \
    -h "$0.hosts" \
    --par 6 \
    'cd ~/.gitrepos && ./update.sh'

wait
