# this host has a battery
set -g status-right "$pane3_color#{?alternate_on,[#{pane_current_command}],#{pane_current_command}} $pane_bold$pane2_bumpercolor«$pane2_color#{?client_prefix, PREFIX ,} #(~/.tmux/battery) $pane1_bumpercolor«$pane1_color %R "

# this host's color is magenta/cyan
setw -g window-status-format "#[fg=magenta,bg=colour235]> #I:#W#F "
setw -g window-status-current-format "#[fg=colour232,bg=magenta,bold]» #I:#W#F "

bind-key R new-window -n root 'sudo su -' \; \
	setw -q window-status-format "#[fg=cyan,bg=colour235]> #I:#W#F " \; \
	setw -q window-status-current-format "#[fg=colour232,bg=cyan,bold]» #I:#W#F "

# dev => green
bind-key C-d new-window 'ssh dev' \; \
	setw -q window-status-format "#[fg=green,bg=colour235]> #I:#W#F " \; \
	setw -q window-status-current-format "#[fg=colour232,bg=green,bold]» #I:#W#F "

# test => yellow
bind-key C-t new-window 'ssh test220' \; \
	setw -q window-status-format "#[fg=yellow,bg=colour235]> #I:#W#F " \; \
	setw -q window-status-current-format "#[fg=colour232,bg=yellow,bold]» #I:#W#F "

# home => red
bind-key C-h new-window -n '' 'ssh home' \; \
	setw -q window-status-format "#[fg=red,bg=colour235]> #I:#W#F " \; \
	setw -q window-status-current-format "#[fg=colour232,bg=red,bold]» #I:#W#F "

#new-window -t startboinc startboinc

# vi: ft=conf
